### ISSUE TITLE
トップページのコンポーネント設計を考える

### ISSUE THREAD

**Issue by piro0919** [shikky0331/shikky#10]
**Is your feature request related to a problem? Please describe.**
今回は Web プロトタイプをかまさないため、フロント側でコンポーネント設計を考える必要があります。

**Describe the solution you'd like**
各ページごとに 1 コンポーネントでも良いですし、container と presentational components に分けるだけでも良いですし、atomic design を導入しても問題ないです。
まずは方針を決めていきましょう。 👍

**Comment by shikky0331** [comment]
@piro0919 
前からAtomic Designを使ってみたかったので、今回はAtomic Designを導入して開発していきたいと思います！🙋‍♂️

**Comment by piro0919** [comment]
@shikky0331 

> 前からAtomic Designを使ってみたかったので、今回はAtomic Designを導入して開発していきたいと思います！🙋‍♂️

了解ですー。
ちょっと今回のプロジェクトの規模感に合っていない感じはありますが、雰囲気だけでも掴んでいただけたらと思います。

Atomic Design のコンポーネント設計をフォルダ構成に落とし込めるようになり次第、また当 Issue は進めていただきたいので、一旦当 Issue はここでストップしましょう。 👍

**Comment by piro0919** [comment]
@shikky0331 

> Atomic Design のコンポーネント設計をフォルダ構成に落とし込めるようになり次第、また当 Issue は進めていただきたいので、一旦当 Issue はここでストップしましょう。 👍

トップページが形になってきたので、本 Issue を再開していきましょう。 👍 
本 Issue の目的はトップページを Atomic Design に落とし込むところまでとします。

rel https://github.com/shikky0331/shikky/blob/main/src/components/templates/Blog/index.tsx

今回のケースでは、以下のように落とし込むのが自然かなーと思います。 👍 

- article のリストに対応するコンポーネントを organisms に作成する
- article に対応するコンポーネントを molecules に作成する
- h3 に対応するコンポーネントを atoms に作成する。
