### ISSUE TITLE
stylelint-config-css-modules を追加する

### ISSUE THREAD

**Issue by shikky0331** [shikky0331/shikky#28]
**Is your feature request related to a problem? Please describe.**
JSXとCSSの命名規則が異なるのを対処したい

**Describe the solution you'd like**
[babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules)を導入する

**Comment by shikky0331** [comment]
@piro0919 
[babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules)を導入したいのですが、ejectしたくないので[craco](https://github.com/gsoft-inc/craco)を使おうと思っています。
この進め方で問題ないでしょうか？🙇‍♂️

[react-app-rewired](https://github.com/timarney/react-app-rewired)は`Create React App 2.0`までしか対応していないみたいなので対象から外しました。

react eject で調べてたらpiroさんの[記事](https://kk-web.link/blog/20200715)出てきました！😊

**Comment by piro0919** [comment]
@shikky0331 

個人的には `babel-plugin-react-css-modules` は今はあまりオススメできないですね。
記事を書いた当時から流行りきらなかったというのもあり、自分なら無難に CSS Modules で組んじゃうかなーと思います。

> JSXとCSSの命名規則が異なるのを対処したい

上記については確かに書かれている内容で認識に相違ないですが、CSS Modules を使用する場合は暗黙の了解になってるのかなと…。

経験として導入したいのであれば悪くないと思いますが、現場レベルであれば今はやらないほうが無難かなと。

**Comment by shikky0331** [comment]
@piro0919 
> 上記については確かに書かれている内容で認識に相違ないですが、CSS Modules を使用する場合は暗黙の了解になってるのかなと…。

そうなのですね！📝 ライブラリ入れなくてもいいのであれば、入れたくないので`"selector-class-pattern": null`をstylelintの設定に追加して対応したいと思います！

**Comment by piro0919** [comment]
@shikky0331 

> そうなのですね！📝 ライブラリ入れなくてもいいのであれば、入れたくないので"selector-class-pattern": nullをstylelintの設定に追加して対応したいと思います！

上記の対応を行うよりは、CSS Modules 用の stylelint の設定を追加するほうがより良いかと思いますが、どうでしょうか。
rel https://www.npmjs.com/package/stylelint-config-css-modules

**Comment by shikky0331** [comment]
@piro0919 
おおー！stylelintをCSS Modules用に設定してくれるpackageがあるのですね！
こちらで対応したいと思います！

ありがとうございます！

**Comment by piro0919** [comment]
@shikky0331 

rel https://github.com/shikky0331/shikky/pull/29#issue-686385262

> stylelint-config-css-modulesを追加しても、stylelint-config-sass-guidelinesでSelector should be written in lowercase with hyphens (selector-class-pattern)のエラーが発生するので"selector-class-pattern": nullを追加しました。

上記について自分の環境でも確認しましたが、`rule` は追加が必要そうですね…。
お手数かけました。 🙇
