### ISSUE TITLE
不要なファイルの削除

### ISSUE THREAD

**Issue by piro0919** [shikky0331/shikky#3]
Is your feature request related to a problem? Please describe.
Create React App の導入により、不要なファイルが存在している。

Describe the solution you'd like
使用しない不要なファイルは削除してください。 👍

**Comment by shikky0331** [comment]
@piro0919 
不要なファイルがどれか理解できていないのですが、`src`, `public`フォルダ以下のファイルは全て削除でいいのでしょうか。。？

**Comment by piro0919** [comment]
@shikky0331 

では `src` と `public` フォルダーの存在意義を調べてみてください。 👍 

ローカル環境で `src` 以下を削除してみたり、`public` 以下を削除してみると、ローカル上での動作はどうなるか、また build した結果どうなるか確認してみるとわかってくると思います。 👀 

少なくとも、GitHub Pages が見れなくなったり、動作しなくなるようなことは避けたいですね。
