### ISSUE TITLE
scriptsコマンドのeslintとstylelintのパスが予定したパスを指し示していない

### ISSUE THREAD

**Issue by shikky0331** [shikky0331/shikky#32]
**Describe the bug**
```
shikky $ echo src/**/*.{tsx,ts}
src/containers/index.tsx src/**/*.ts
```

```
shikky $ echo src/**/*.scss
src/styles/global.scss
```

**Expected behavior**
- src以下のtsx, tsファイル全て指し示す
- src以下のscssファイルを全て指し示す

**Comment by piro0919** [comment]
@shikky0331 

ちょっと Issue の内容が把握できていないので、現状何が良くないのが教えて頂きたいです。 🙇

**Comment by shikky0331** [comment]
@piro0919 
```
shikky $  echo src/**/*.{tsx,ts}
src/containers/index.tsx src/**/*.ts

shikky $  echo "src/**/*.{tsx,ts}"
src/**/*.{tsx,ts}
```
本当は`src/**/*.{tsx,ts}`でsrc以下の`ts, tsx`ファイルを全てeslinにかけたいのですが、現状は上のパス指定になっているので`src/containers/index.tsx src/**/*.ts`のファイルしか指し示していない状態になっています🙇‍♂️
