### ISSUE TITLE
Component型定義のつけ忘れをeslintで検知したい

### ISSUE THREAD

**Issue by shikky0331** [shikky0331/shikky#34]
**Is your feature request related to a problem? Please describe.**
Componentに型定義をつけ忘れてしまうことがある。
https://github.com/shikky0331/shikky/pull/31#discussion_r667569588

**Describe the solution you'd like**
eslintでComponentに型定義がされていなかったら検知できるようにする。

**Comment by shikky0331** [comment]
VFC or FC を指定する eslint はなさそう。。

**Comment by shikky0331** [comment]
https://github.com/typehut/eslint-plugin/blob/main/docs/rules/typescript-react-component-type.md
これで一応できそうかも。。

**Comment by piro0919** [comment]
@shikky0331 

rel https://github.com/typescript-eslint/typescript-eslint/blob/v4.26.1/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md

上記のルールで対応できると思いますー。
設定にちょっと抜けがありそうなので、以下のドキュメントに沿ってみてください。 👍 

rel https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md

<img width="648" alt="image" src="https://user-images.githubusercontent.com/30312044/125726852-ac3c8158-2e0c-43f5-9305-7d168568eb1b.png">

**Comment by shikky0331** [comment]
@piro0919 
ありがとうございます！！！
参考にしてやってみます🙌
