### ISSUE TITLE
コンポーネントの粒度が Atomic Design に沿っているか見直す

### ISSUE THREAD

**Issue by piro0919** [shikky0331/shikky#44]
**Describe the bug**
一部の presentational components の粒度が Atomic Design に沿っていない。

**Expected behavior**
コンポーネントのスタイリングの仕様を見返した上で直しましょう。 😄

**Comment by shikky0331** [comment]
@piro0919 
```
molecules: Article ✅
  atoms: ArticeTitle ✅
  atoms: ArticleDate
  atoms: ArticleIntroduction

organisms: Header ✅
  atoms: Logo
  molecules or organisms: HeaderNav
    atoms: Link

organisms: Footer ✅
  atoms: CopyOnWrite
```
上記のイメージでAtomic Designに落とし込んでいこうかと思います。
`HeaderNav`は`organisms`か`molecules`か悩み中です。。

**Comment by piro0919** [comment]
@shikky0331 

ちょっと Issue の意図と認識がずれているかもです。 👀 

個人的にですが、コンポーネントの粒度自体はあまり細かくする必要はないと思っています。
（本来 Web デザイナーが行うべき作業ですしね）

本 Issue では `コンポーネントのスタイリングの仕様を見返した上で直しましょう。` を目的としていますので、現時点で Atomic Design に沿っていないスタイリングを直してもらえれば十分ですね。 👍 
以前お話したリストのマージンなど、そのあたりの直して頂ければと。 🙇

**Comment by shikky0331** [comment]
@piro0919 
すみません。タスクの内容を把握できてなかったです🙇‍♂️

> 個人的にですが、コンポーネントの粒度自体はあまり細かくする必要はないと思っています。

なるほどです！意味のある粒度であれば、細かくした方がいいのかと思っていました！

> 本 Issue では コンポーネントのスタイリングの仕様を見返した上で直しましょう。 を目的としていますので、現時点で Atomic Design に沿っていないスタイリングを直してもらえれば十分ですね。 👍

承知しました。前回教えてもらったことを参考に修正したいと思います！
