### ISSUE TITLE
Sass の導入について

### ISSUE THREAD

**Issue by piro0919** [shikky0331/shikky#5]
**Is your feature request related to a problem? Please describe.**
CSS Modules を使用して開発を行っていただく予定ですが、Sass の使用についてはおまかせします。
使用される場合は Sass が動作する環境を作成してみてください。 👍 

**Additional context**
- https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/
- https://create-react-app.dev/docs/adding-a-sass-stylesheet/

**Comment by shikky0331** [comment]
@piro0919 
Sassは使用したいので導入してみます！
