### ISSUE TITLE
static な html に対応する

### ISSUE THREAD

**Issue by piro0919** [shikky0331/shikky#53]
**Is your feature request related to a problem? Please describe.**
GitHub Pages において、各ブログページでリロードを行った際、404 が表示される。

**Describe the solution you'd like**
[react-snap](https://www.npmjs.com/package/react-snap) を導入し、spa かつ static な状態にする。

**Additional context**
[Pre-Rendering into Static HTML Files](https://create-react-app.dev/docs/pre-rendering-into-static-html-files/)

**Comment by shikky0331** [comment]
Because 404 error still occurs even after refreshing a page.
