### ISSUE TITLE
コミット前に lint を実行する

### ISSUE THREAD

**Issue by piro0919** [shikky0331/shikky#65]
**Is your feature request related to a problem? Please describe.**
PR を確認していると、ちょくちょく lint の抜けが見つかる。
rel https://github.com/shikky0331/shikky/pull/64#discussion_r696722921

**Describe the solution you'd like**
コミット前に lint を実行し、lint の漏れを防ぐようにする。

**Additional context**
[husky](https://www.npmjs.com/package/husky) の導入を検討してみましょう。 👍

**Comment by shikky0331** [comment]
タスク作成ありがとうございます！！🐩

https://github.com/shikky0331/shikky/blob/main/package.json#L92
huskyは導入しているのですが、eslintの`warning`がコミットするときに弾かれていなかったので設定を見直します！
