### ISSUE TITLE
ページ設計を考える

### ISSUE THREAD

**Issue by piro0919** [shikky0331/shikky#9]
**Is your feature request related to a problem? Please describe.**
サイト全体のページ設計を考えてみてください。

**Describe the solution you'd like**
今回はブログサイトということなので、ひとまず最低限の構成として 2 画面作れば良いかなーと思いました。

- トップページ兼ブログのインデックスページ
- 各ブログページ

ページ設計が決まりましたら `react-router-dom` の導入から、各 container components を切るところまで進めてください。 👍

**Comment by shikky0331** [comment]
@piro0919 
> 今回はブログサイトということなので、ひとまず最低限の構成として 2 画面作れば良いかなーと思いました。

そうですね！最初は提示していただいた2画面を作成したいと思います🐪

**Comment by piro0919** [comment]
@shikky0331 

> そうですね！最初は提示していただいた2画面を作成したいと思います🐪

了解ですー。 👍 

> ページ設計が決まりましたら react-router-dom の導入から、各 container components を切るところまで進めてください。 👍

したらばこの Issue ではここまでを目的としましょう。 👍
